# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(915, 554)
        self.btn_search_excel_1 = QtWidgets.QPushButton(parent=Dialog)
        self.btn_search_excel_1.setGeometry(QtCore.QRect(820, 20, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_search_excel_1.setFont(font)
        self.btn_search_excel_1.setObjectName("btn_search_excel_1")
        self.lineEdit_excel_1 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_excel_1.setGeometry(QtCore.QRect(190, 20, 621, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_excel_1.setFont(font)
        self.lineEdit_excel_1.setText("")
        self.lineEdit_excel_1.setObjectName("lineEdit_excel_1")
        self.label_1 = QtWidgets.QLabel(parent=Dialog)
        self.label_1.setGeometry(QtCore.QRect(20, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("새굴림")
        font.setPointSize(15)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(20, 70, 761, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.btn_execute = QtWidgets.QPushButton(parent=Dialog)
        self.btn_execute.setGeometry(QtCore.QRect(670, 160, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_execute.setFont(font)
        self.btn_execute.setObjectName("btn_execute")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 220, 91, 31))
        font = QtGui.QFont()
        font.setFamily("새굴림")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit_log = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit_log.setGeometry(QtCore.QRect(20, 250, 881, 291))
        self.textEdit_log.setObjectName("textEdit_log")
        self.line_9 = QtWidgets.QFrame(parent=Dialog)
        self.line_9.setGeometry(QtCore.QRect(20, 210, 871, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("새굴림")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_search_excel_2 = QtWidgets.QPushButton(parent=Dialog)
        self.btn_search_excel_2.setGeometry(QtCore.QRect(820, 100, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_search_excel_2.setFont(font)
        self.btn_search_excel_2.setObjectName("btn_search_excel_2")
        self.lineEdit_excel_2 = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_excel_2.setGeometry(QtCore.QRect(190, 100, 621, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_excel_2.setFont(font)
        self.lineEdit_excel_2.setText("")
        self.lineEdit_excel_2.setObjectName("lineEdit_excel_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_search_excel_1.setText(_translate("Dialog", "검색"))
        self.label_1.setText(_translate("Dialog", "쿠팡 엑셀 위치"))
        self.btn_execute.setText(_translate("Dialog", "실행"))
        self.label_3.setText(_translate("Dialog", "로그"))
        self.textEdit_log.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "리포트 엑셀 위치"))
        self.btn_search_excel_2.setText(_translate("Dialog", "검색"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
